#!/usr/bin/env python3
"""Import a rendered X capture into date-grouped journal pages, without editing other diaries."""
import argparse, hashlib, html, json, re
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import urlparse, parse_qs
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
MARKER = '<!-- generated by scripts/import-x-capture.py -->'

def escape(text):
    return re.sub(r'([\\`*_{}\[\]<>#])', r'\\\1', text)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('capture', type=Path)
    parser.add_argument('--replace-initial-preview', action='store_true')
    args = parser.parse_args()
    capture = json.loads(args.capture.read_text())
    rows = {r['url']: r for r in capture['posts'] if re.fullmatch(r'https://x.com/itsuki_maer/status/\d+', r['url'])}
    media_dir = ROOT / 'public/assets/x'
    media_dir.mkdir(parents=True, exist_ok=True)
    # Keep the largest rendition actually observed for each image; never invent source URLs.
    sizes = {'orig': 9999, 'large': 2048, 'medium': 1200, 'small': 680, 'thumb': 150}
    choices = {}
    for row in rows.values():
        for image in row.get('images', []):
            url = image['src']; parsed = urlparse(url)
            if parsed.scheme != 'https' or parsed.hostname != 'pbs.twimg.com': continue
            name = parse_qs(parsed.query).get('name', ['small'])[0]
            score = sizes.get(name, int(name.split('x')[0]) if name.split('x')[0].isdigit() else 0)
            if parsed.path not in choices or choices[parsed.path][0] < score: choices[parsed.path] = (score, url)
    def download(item):
        key, (_, url) = item
        fmt = parse_qs(urlparse(url).query).get('format', [Path(key).suffix.lstrip('.') or 'jpg'])[0]
        if fmt not in ('jpg', 'jpeg', 'png', 'webp', 'gif'): return key, None
        name = hashlib.sha256(key.encode()).hexdigest()[:20] + '.' + fmt
        path = media_dir / name
        try:
            if not path.exists():
                with urlopen(Request(url, headers={'User-Agent': 'Mozilla/5.0'}), timeout=30) as res:
                    payload = res.read()
                    if not res.headers.get('Content-Type', '').startswith('image/'): raise ValueError('not an image')
                path.write_bytes(payload)
            return key, '/assets/x/' + name
        except Exception as error:
            return key, None
    with ThreadPoolExecutor(max_workers=8) as pool: media = dict(pool.map(download, choices.items()))
    groups = defaultdict(list)
    for row in rows.values():
        local = datetime.fromisoformat(row['date'].replace('Z', '+00:00')) + timedelta(hours=9)
        row = dict(row, local_date=local.strftime('%Y-%m-%d'), local_time=local.strftime('%H:%M'))
        groups[row['local_date']].append(row)
    for day, posts in sorted(groups.items()):
        posts.sort(key=lambda p:p['date'])
        path = ROOT / 'src/content/blog/ja/journals' / day[:4] / day[5:7] / (day + '-x.md')
        if path.exists() and MARKER not in path.read_text():
            if not (args.replace_initial_preview and day == '2026-09-05'): raise SystemExit(f'Refusing to overwrite {path}')
        # Preserve the editorial title stored in Markdown during subsequent imports.
        title = f'{day}｜Xの日記'
        if path.exists():
            match = re.search(r'^title: (.+)$', path.read_text().split('---', 2)[1], re.M)
            if match:
                title = json.loads(match.group(1))
        fronts = {'lang':'ja','date':day,'category':'journals','featured':False,'coverImage':'','title':title,'tags':['X','日記'],'summary':f'Xに投稿した{len(posts)}件の記録。' + ' / '.join(p['text'].split('\n')[0][:48] for p in posts if p['text'])[:160]}
        out = ['---'] + [f'{k}: {json.dumps(v,ensure_ascii=False)}' for k,v in fronts.items()] + ['---', MARKER, '']
        for p in posts:
            pid=p['url'].rsplit('/',1)[-1]
            out += [f'## {p["local_time"]}', '', f'<span id="x-{pid}"></span>', '']
            text=p['text']
            # Render displayed external URL labels as their actual recorded destinations.
            for link in p['links']:
                if link['href'].startswith('https://t.co/') and link['text'] and link['text'] in text:
                    text=text.replace(link['text'],link['href'])
            out += [escape(text).replace('\n', '  \n') if text else '（本文のないメディア投稿）', '']
            own_photo_links = list(dict.fromkeys(l['href'] for l in p['links'] if re.fullmatch(re.escape(p['url'])+r'/photo/\d+',l['href'])))
            photos=[i for i in p['images'] if i['alt']=='Image'][:len(own_photo_links)]
            sources=list(dict.fromkeys(media.get(urlparse(i['src']).path) for i in photos))
            sources=[s for s in sources if s]
            if sources:
                out += ['<div class="x-photo-grid">']
                out += [f'<img src="{src}" alt="{day} {p["local_time"]}の投稿写真 {i+1}" loading="lazy" />' for i,src in enumerate(sources)]
                out += ['</div>', '']
            out += [f'[Xで元の投稿を見る]({p["url"]})', '']
        path.parent.mkdir(parents=True,exist_ok=True);path.write_text('\n'.join(out))
    report = {'profile':capture['profile'],'capturedAt':capture['capturedAt'],'ownPosts':len(rows),'days':len(groups),'dateFrom':min(groups),'dateTo':max(groups),'profileCount':capture['profileCount'],'reposts':capture.get('reposts',[]),'imagesSaved':sum(bool(v) for v in media.values()),'imageFailures':[choices[k][1] for k,v in media.items() if not v],'officialArchive':False,'videoFilesSaved':0,'notes':['Rendered browser capture, not a guarantee of deleted or hidden post coverage.','Images are observed display renditions, not guaranteed originals.','Repost timestamp not exposed; do not assign original publication date as repost date.']}
    (ROOT/'x-backup-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
    print(json.dumps(report,ensure_ascii=False,indent=2))

if __name__ == '__main__': main()
